=== tiwm22-ti-g06/tiwm22-ti-g06/source/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.juicers.org"
    xmlns:tns="http://www.juicers.org"
    elementFormDefault="qualified"
    attributeFormDefault="qualified">

    <simpleType name="nomeType">
        <restriction base="string">
            <minLength value="0"/>
            <maxLength value="50"/>
        </restriction>
    </simpleType>

    <simpleType name="familiaType">
        <restriction base="string">
            <minLength value="0"/>
            <maxLength value="50"/>
        </restriction>
    </simpleType>

    <simpleType name="subfamiliaType">
        <restriction base="string">
            <minLength value="0"/>
            <maxLength value="50"/>
        </restriction>
    </simpleType>


    <complexType name="animalType">
        <sequence>
            <element name="nome" type="tns:nomeType" minOccurs="0" maxOccurs="1"/>
            <element name="familia" type="tns:familiaType" minOccurs="0" maxOccurs="1"/>
            <element name="subfamilia" type="tns:subfamiliaType" minOccurs="0" maxOccurs="1"/>
        </sequence>
    </complexType>
        

    <element name="dados">
        <complexType>
            <sequence>
                <element name="animal" type="tns:animalType" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

</schema>

=== tiwm22-ti-g06/tiwm22-ti-g06/source/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<dados xmlns="http://www.juicers.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.juicers.org data.xsd">

    <animal>
        <nome>Leopardo das neves</nome>
        <familia>Felinos</familia>
        <subfamilia>Pantherinae</subfamilia>
    </animal>
    <animal>
        <nome>Tigre dentes-de-sabre</nome>
        <familia>Felinos</familia>
        <subfamilia>Machairodontinae</subfamilia>
    </animal>
    <animal>
        <nome>Gato Dourado Africano</nome>
        <familia>Felinos</familia>
        <subfamilia>Felineos</subfamilia>
    </animal>
</dados>
